version: "3"
services:
  # rabbitmq:
  #   image: rabbitmq:3
  #   ports:
  #     - 5672:5672      
  rabbit-management:
    image: rabbitmq:3-management
    ports:
      - 5672:5672      
      - 15672:15672